name = "ElectricWires"
uuid = "a6e744fb-b06e-4c79-977f-74d170207450"
authors = ["Bodo Kaiser"]
repo = "https://github.com/rydyb/ElectricWires.jl"
version = "0.1.0"

[deps]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"

[compat]
julia = "1"
DynamicQuantities = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
